"$schema" = 'https://starship.rs/config-schema.json'

format = "$env_var$debian_chroot$ssh$container$user$hostname$directory$git_branch$git_commit$git_state$git_status$git_metrics$docker_context$character"

[character]
success_symbol = '[\$](bold white)'
error_symbol = '[\$](bold red)'

[directory]
format = '[$path](bold blue)[$read_only]($read_only_style)'
truncate_to_repo = false

[git_commit]
commit_hash_length = 7
only_detached = true

[git_branch]
format = ':[$branch(:$remote_branch)](bold green)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
deleted = 'Ã—'
